app:
  name: "@project.artifactId@"
  version: "@project.version@"

logging:
  level:
    ROOT: "INFO"
    org.springframework: "INFO"
    net.playground.reactive.demo.reactive.mongo.client: "INFO"

server:
  port: 8080
  servlet:
    context-path: "/reactive-mongo-client"

# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/reactive-demo/reactive-mongo-client.log"
