spring:
  profiles:
    include:
    - "default"
  data:
    mongodb:
      host: "localhost"
      port: 27017
      authentication-database: "customerdb"
      database: "customerdb"
      username: "customer"
      password: "welcome1"

logging:
  level:
    net.playground.reactive.demo.reactive.mongo.client: "DEBUG"

server:
  port: 9081

management:
  endpoint:
    logfile:
      external-file: "logs/reactive-mongo-client.log"

